CREATE TABLE IF NOT EXISTS teams (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
    name VARCHAR(100) UNIQUE NOT NULL,
);

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(16) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    team_id INTEGER REFERENCES teams (id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
);

CREATE TYPE IF NOT EXISTS status_enum AS ENUM('OPEN', 'MERGED');

CREATE TABLE IF NOT EXISTS pull_requests (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author_id VARCHAR(16) NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    status status_enum NOT NULL,
);
